services:
  cometbackup:
    image: tony1661/cometbackup-docker:latest
    build:
      context: .
      dockerfile: dockerfile
    container_name: cometbackup
    env_file: "comet.env"
    volumes:
      - /home/tfernandez/Downloads:/data
    restart: unless-stopped